# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190208_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='avatars/default.jpg', upload_to='avatars/'),
        ),
    ]
